#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Extract stl file of the surface
FILE=./constant/triSurface/Bolund_GeoTIFF_file.stl
if [ ! -f "$FILE" ]; then
    echo "Unpacking BolundGeoTiff.tar.gz"
    cd constant/triSurface
    tar -xzvf Bolund_GeoTIFF.tar.gz
    cd ../../
fi

# Set controlDict, fvSchemes, and fvSolution for the moveMesh solver
cp system/controlDict.moveMesh system/controlDict
cp system/fvSchemes.moveMesh system/fvSchemes
cp system/fvSolution.moveMesh system/fvSolution
cp system/dynamicMeshDict constant/dynamicMeshDict

# Build the basic mesh
# --------------------
echo 'Running blockMesh'
blockMesh > log.blockMesh 2>&1

# Decompose the mesh (for moveMesh)
# --------------------------------
echo 'Running decomposePar'
decomposePar > log.decomposePar.1 2>&1

# Imprint Bolund Hill into the mesh using moveMesh
# -----------------------------------------------

# Get number of cores from the setUp file
nCores=$(foamDictionary -entry nCores -value setUp)

# Run moveMesh solver
echo 'Running moveMesh'
mpirun -np $nCores moveMesh -parallel > log.moveMesh 2>&1

# Reconstruct the mesh
# --------------------
echo 'Running reconstructPar'
reconstructPar -latestTime > log.reconstructPar.1 2>&1

rm -r processor*

# Mesh refinement near the surface
# --------------------------------

# Set controlDict, fvSchemes, and fvSolution for the simpleFoam solver
# here as refinemesh uses some inputs from controlDict (which differs from
# the moveMesh controlDict)
cp system/controlDict.simpleFoam system/controlDict
cp system/fvSchemes.simpleFoam system/fvSchemes
cp system/fvSolution.simpleFoam system/fvSolution

echo 'Running topoSet'
topoSet -latestTime > log.topoSet 2>&1

echo 'Running refineMesh'
refineMesh > log.refineMesh 2>&1

# Check mesh quality
# ------------------
echo 'Running checkMesh'
checkMesh > log.checkMesh 2>&1

# Copy over the field variables from the zero folder
# --------------------------------------------------
echo 'Copying field variables from 0 folder'
cp 0/U 51/U
cp 0/epsilon 51/epsilon
cp 0/k 51/k
cp 0/nut 51/nut
cp 0/p 51/p

# Renumber mesh
# -------------
echo 'Running renumberMesh'
renumberMesh -latestTime -overwrite > log.renumberMesh 2>&1

# initialize fields?

# Decompose the mesh (for simpleFoam)
# -----------------------------------
echo 'Running decomposePar'
decomposePar -force > log.decomposePar.2 2>&1

# Run simpleFoam
# --------------
# Remove dynamicMeshDict from constant, otherwise simpleFoam does not work
rm constant/dynamicMeshDict

# Run the solver
echo 'Running simpleFoam'
mpirun -np $nCores simpleFoam -parallel > log.simpleFoam 2>&1
